-- CreateEnum
CREATE TYPE "FormaPago" AS ENUM ('EFECTIVO', 'QR', 'MIXTO');

-- AlterTable
ALTER TABLE "Venta" ADD COLUMN     "formaPago" "FormaPago" NOT NULL DEFAULT 'EFECTIVO',
ADD COLUMN     "montoEfectivo" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "montoQr" DOUBLE PRECISION NOT NULL DEFAULT 0;
